version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      runas: ec2-user
  AfterInstall:
    - location: clean_pull_and_run.sh
      runas: ec2-user
