version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      runas: ec2-user
  ApplicationStart:
    - location: clean_pull_and_run.sh
      runas: ec2-user
